### ISSUE TITLE
Pymqi latest version 9.1.3, How to specify SSL cipher spec? 

### ISSUE THREAD

**Issue by gowdhammurthi** [dsuch/pymqi#141] opened 2019-12-09 07:56 UTC
```
CONNECTION_DEFINITION = pymqi.CD()
CONNECTION_DEFINITION.ChannelName = $CHANNEL
CONNECTION_DEFINITION.ConnectionName =$ CONN_INFO
CONNECTION_DEFINITION.ChannelType = pymqi.CMQC.MQCHT_CLNTCONN
CONNECTION_DEFINITION.TransportType = pymqi.CMQC.MQXPT_TCP
CONNECTION_DEFINITION.SSLCipherSpec = $SSL_CIPHER_SPEC,
```

The above format does not put the SSL_CIPHER_SPEC. Am I doing something wrong after the update? Can someone explain on this? I am still using pymqi==1.9.2 . It would be a lot helpful.

Thanks

**Comment by dsuch** [comment] 2019-12-09 08:52
Hello @gowdhammurthi,

what you are showing is your own code that is not even Python - likely, no one will be able to understand where $SSL_CIPHER_SPEC comes from and how you populate it.

**Comment by gowdhammurthi** [comment] 2019-12-09 10:34
I am sorry, I meant os.environ['ssl_cipher_spec']. Like environment variable, Its actual value is TLS_RSA_WITH_AES_256_CBC_SHA256. $CHANNEL, $CONN_INFO, $SSL_CIPHER_SPEC, all these come from environment variables.

**Comment by dsuch** [comment] 2019-12-09 12:01
@gowdhammurthi - please understand that this issue tracker is about PyMQI alone.

An occasional side-question about MQ usage is not out of place but you are showing the source code of your own program - it is not possible to know what may be the root cause of what you are observing.

If you would like to have assistance in this tracker, please post a self-contained Python code that is to do with PyMQI directly. This needs to be something that myself or other people can just take and use in their own systems.

Thanks.

**Comment by JoshMcMQ** [comment] 2019-12-09 12:15
There is a good example already at:

https://github.com/dsuch/pymqi/blob/master/code/examples/ssl_tls.py

I suspect it is not working because you are not providing a key repository location, due example:

```
key_repo_location = "/var/mqm/ssl-db/client/KeyringClient"
sco = pymqi.SCO()
sco.KeyRepository = key_repo_location
qmgr = pymqi.QueueManager(None)
qmgr.connect_with_options(queue_manager, CONNECTION_DEFINITION, sco)
```

**Comment by gowdhammurthi** [comment] 2019-12-09 16:34
`import logging

import pymqi

logging.basicConfig(level=logging.INFO)

queue_manager = "TESTQA"
channel = "CLOUD.PYAPP.SVRCONN".encode('utf-8')
host = "testhostipaddress"
port = "30668"
queue_name = "DEV.QUEUE.1".encode('utf-8')
conn_info = ("%s(%s)" % (host, port)).encode('utf-8')
ssl_cipher_spec = "TLS_RSA_WITH_AES_256_CBC_SHA256".encode('utf-8')
key_repo_location = "key_repo/key".encode('utf-8')
message = "Hello from Python!".encode('utf-8')

cd = pymqi.CD()
cd.ChannelName = channel
cd.ConnectionName = conn_info
cd.ChannelType = pymqi.CMQC.MQCHT_CLNTCONN
cd.TransportType = pymqi.CMQC.MQXPT_TCP
cd.SSLCipherSpec = ssl_cipher_spec

sco = pymqi.SCO()
sco.KeyRepository = key_repo_location

qmgr = pymqi.QueueManager(None)
qmgr.connect_with_options(queue_manager, cd, sco)

put_queue = pymqi.Queue(qmgr, queue_name)
put_queue.put(message)

get_queue = pymqi.Queue(qmgr, queue_name)
logging.info("Here's the message again: [%s]" % get_queue.get())

put_queue.close()
get_queue.close()
qmgr.disconnect()`

In the above code, which is taken from [https://github.com/dsuch/pymqi/blob/master/code/examples/ssl_tls.py]
If pymqi==1.9.2 is used ,
Output is `INFO:root:Here's the message again: [b'Hello from Python!']`
If pymqi==1.9.3 is used,
Output is 
`Traceback (most recent call last):
  File "test.py", line 28, in <module>
    qmgr.connect_with_options(queue_manager, cd, sco)
  File "/usr/local/lib/python3.7/dist-packages/pymqi/__init__.py", line 1423, in connect_with_options
    raise MQMIError(rv[1], rv[2])`

This is the exact problem, I am facing even when I run my original code.

**Comment by JoshMcMQ** [comment] 2019-12-09 16:46
Try adding this:

```
cd = pymqi.CD(Version=pymqi.CMQXC.MQCD_VERSION_11)
```

**Comment by gowdhammurthi** [comment] 2019-12-09 17:54
@JoshMcMQ, Thank you. It is fixed now!!

**Comment by dsuch** [comment] 2019-12-09 17:59
Hi @JoshMcMQ - perhaps we should make MQCD_VERSION_11 the default one in this case to prevent such situations in the future?

**Comment by JoshMcMQ** [comment] 2019-12-09 18:47
It is actually MQCD_VERSION_7 where cipher was added to the CD structure, MQ will ignore it if version is lower than where added.   The same holds true in C that you must set it. I think the idea in the latest patch was to have it have the same default as IBM has instead of the current version that it was compiled with.  IBM has chosen to leave the default as v6 which is what was there in 5.2 of MQ.  More details in these two links:

https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_7.5.0/com.ibm.mq.ref.dev.doc/q109070_.htm (some of the historical comments are removed in the later KC page)

https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.ref.dev.doc/q109070_.htm

My thought is check in the connect with options if `SSLCipherSpec` is set,  if set and CD version less than 7 bump it to 7.

On the other hand v7 has been around since 5.3.  5 3, 6, 7.0, 7.1, 7.5 are all out of support from IBM, even v8.0 goes out of support in April 2020.  We may be safe in defaulting to v7 🙂.

**Comment by gowdhammurthi** [comment] 2019-12-09 18:56
@JoshMcMQ Thank you! It is very clear and helpful. I think we can close this issue.

**Comment by JoshMcMQ** [comment] 2019-12-09 19:06
Please leave open as the pymqi maintainer @dsuch and I are discussing the issue.

**Comment by dsuch** [comment] 2019-12-09 19:28
Thanks @JoshMcMQ - this is a good idea and I will implement it, this is a low-level library but still we can make everyone's life a bit easier in this way.

I will do it under this ticket and later release 1.9.4 with this change.

**Comment by dsuch** [comment] 2019-12-09 19:36
@JoshMcMQ - just one question. I am looking at how we set username/password via MQCSP fields and it works as is already.

Yet, you said that something similar to SSLCipherSpec could be done here too - but I just do not see under what conditions anything should be changed from the defaults that we have now?

There is more logic behind but for all practical purposes, we always run with MQCNO_VERSION_5 which should nicely enable username/password authentication?

**Comment by JoshMcMQ** [comment] 2019-12-09 21:12
@dsuch I agree with you, it looks like `#ifdef PYMQI_FEATURE_SSL` is alway true,  so should always be at v5 which is what is needed.   In C code the default is v1 so you have to set to v5 which is what I was confusing it with.   Same as CD v7, CNO v5 has been around since 5.3.

**Comment by JoshMcMQ** [comment] 2019-12-10 10:54
@dsuch we did discuss the same section of code in https://github.com/dsuch/pymqi/issues/78, I never got the time to focus on the updates discussed there.

**Comment by dsuch** [comment] 2019-12-10 13:39
@JoshMcMQ - I pushed a commit to enable CD v7 in case SSLCipherSpec is used and version is less than 7. I wanted to put out a new PyMQI release but perhaps this can wait until there is another change to go with it soon.

Also, I pushed [a commit in a separate branch here](https://github.com/dsuch/pymqi/commit/b51d87ce77d199811ea58d59890ddcb9f3ea6945) that sets up MQCD Version and StrucLength automatically based on current MQ version.

I think we used to have it before but, for reasons that escape me now, it was done away with in favour of MQCD_VERSION_6.

I leave this other commit for posterity in case we would like to get back to it at some point.

**Comment by JoshMcMQ** [comment] 2019-12-10 17:34
Can we get rid of sco if not passed, the default provides no value.

See https://github.com/dsuch/pymqi/issues/78#issuecomment-428066147

**Comment by JoshMcMQ** [comment] 2019-12-10 17:37
I think leaving it default to mqcd v6 is good with the updates you made to increase it to v7 if tls is used. 

Setting it based on complied version means that it won't work against MQ libraries from versions prior to when that mqcd version was added.

**Comment by JoshMcMQ** [comment] 2019-12-10 17:44
Noticed this will break

```
cd.pack() if cd else None
```

With the change cd will anyways be set, it should remain set only if passed in.  Default cd provides no value and breaks CCDT usage.

**Comment by dsuch** [comment] 2019-12-10 17:52
Thanks, that makes sense, I have just pushed a commit with both changes.

**Comment by JoshMcMQ** [comment] 2019-12-10 20:25
Will this if be ok if cd is None?

```
if cd.SSLCipherSpec and cd.Version < CMQC.MQCD_VERSION_7:
```

**Comment by dsuch** [comment] 2019-12-11 06:19
Thanks for spotting it, this is done.

**Comment by chughts** [comment] 2019-12-11 15:21
Please be aware that for CCDT compatibility it must continue to be possible to exclude the cd from the underlying Connx call.

**Comment by JoshMcMQ** [comment] 2019-12-11 15:44
@chughts Do you see a problem with the changes? They look good to me.

**Comment by dsuch** [comment] 2019-12-11 15:52
@chughts Do you mean that, in C terms, MQCNO's ClientConnPtr should be NULL by default? If so, then yes, this will be the case.

**Comment by JoshMcMQ** [comment] 2019-12-12 13:38
@chughts do the latest updates look good,  can you test with ccdt and without before it is released?

**Comment by chughts** [comment] 2019-12-12 14:27
@JoshMcMQ I can, but won't have much bandwidth until after the holiday period.

**Comment by JoshMcMQ** [comment] 2019-12-13 14:27
@chughts I think that will be fine, as the updates are not critical, there is a work around as mentioned in comments above.

**Comment by dsuch** [comment] 2019-12-14 10:06
@JoshMcMQ - I brought back the default CD and SCO objects to connect_with_options.

The changes introduced a couple of days ago were fine as long as connect_with_options was concerned in isolation.

But people will also use the pymqi.connect shortcut, which goes through connect_tcp_client which in turn always gives a CD to connect_with_options.

The increasing of cd.Version to 7 part is still in use, I just reverted the change of CD and SCO to None objects.

I tested it with various examples and it just turned out that to make it run with None we would need some works on the C level in pymqe.c for which I do not have time right now - as things stand today, pymqe.c's MQCONNX cannot accept None in that place.

**Comment by JoshMcMQ** [comment] 2019-12-14 12:17
@dsuch cd has been set to None be default since https://github.com/dsuch/pymqi/pull/116 was merged.   This allowed user/pass to work with CCDTs.  Even if you revert default sco behavior you should leave cd = None behavior as it was.

**Comment by dsuch** [comment] 2019-12-14 12:46
Ah, yes, CCDTs, let me look into it again in that case.

**Comment by dsuch** [comment] 2019-12-14 14:55
@JoshMcMQ This is done in cf6b84c6eb5b8c45fab24da4c00239e4174d9801.

**Comment by JoshMcMQ** [comment] 2019-12-14 15:24
@dsuch  the changes look good. 

If you want to continue with sco work the modifications should be simple. 

For cd we have:

```
if(mqcd) {
    cno.ClientConnPtr = (MQCD *)mqcd;
  }
```

For sco we currently have this:

```
#ifdef PYMQI_FEATURE_SSL
  cno.Version = MQCNO_VERSION_5;
  cno.SSLConfigPtr =  (MQSCO *)sco;
```

Just change it to:

```
#ifdef PYMQI_FEATURE_SSL
  cno.Version = MQCNO_VERSION_5;
if(sco) {
    cno.SSLConfigPtr =  (MQSCO *)sco;
  }
```

**Comment by JoshMcMQ** [comment] 2020-01-11 19:01
@dsuch or @SeyfSV, do the changes I proposed above look ok to you.   Would you make the change if you have time and agree.

**Comment by SeyfSV** [comment] 2020-01-12 10:40
@JoshMcMQ , `SSLConfigPtr`field defined in MQCNO_VERSION_4. Why do you use MQCNO_VERSION_5?

**Comment by JoshMcMQ** [comment] 2020-01-12 13:25
That is what it is already set to, and if changed to 4 you break the MQCSP logic unless you add something to set it to 5 if MQCSP.

**Comment by SeyfSV** [comment] 2020-01-12 13:29
OK
It looks good for me

**Comment by JoshMcMQ** [comment] 2020-01-12 13:39
Thank you for reviewing.

The other change is in `code/pymqi/__init__.py` to leave sco set to None unless passed in.

This was in https://github.com/dsuch/pymqi/commit/91ccd2ab91cbe8bcd417ba95c09744ea8d83b0bd but backed out later.

**Comment by SeyfSV** [comment] 2020-01-13 10:08
Yes, I saw it. If it does not break anything - why not?
I think, we need some tests to cover `connect_with_options` with/without MQCD and MQSCO.

**Comment by salapat11** [comment] 2020-01-14 22:54
How to use connect_with_options with SSL and user id and password?  Where should the userid and password be set?

**Comment by JoshMcMQ** [comment] 2020-01-15 02:55
> How to use connect_with_options with SSL and user id and password? Where should the userid and password be set?

Something like this:
```
sco = pymqi.SCO()
sco.Version = CMQC.MQSCO_VERSION_4
qmgr.connect_with_options(queueManager, user=user, password=password, cd=cd, opts=connection_option, sco=sco)
```

**Comment by salapat11** [comment] 2020-01-15 02:57
Thank you.  That works 👍

**Comment by SeyfSV** [comment] 2020-02-17 17:08
Checked. Closed.

**Closed by SeyfSV** 2020-02-17 17:08 UTC
