### ISSUE TITLE
Memory leak on connection failure using `QueueManager.connect_with_options`

### ISSUE THREAD

**Issue by AlexandreYang** [dsuch/pymqi#208] opened 2020-06-17 14:04 UTC
Hi, it seems the `QueueManager.connect_with_options` might have a memory leak when it fails.

I used `@profile` from [memory-profiler](https://pypi.org/project/memory-profiler/) for the profiling.

As you can see in the profiling results, the memory increases with each call to `QueueManager .connect_with_options`.

You can run the script using `python -m memory_profiler myscript.py`.

MQ Client version: 9.1.3.0

## Full script

```python
import pymqi
from memory_profiler import profile


@profile(precision=4)
def profiled_connect():
    cd = pymqi.CD()
    cd.ChannelName = b'abc'
    cd.ConnectionName = b'abc'
    cd.ChannelType = pymqi.CMQC.MQCHT_CLNTCONN
    cd.TransportType = pymqi.CMQC.MQXPT_TCP
    cd.Version = 6
    cd.SSLCipherSpec = b'mycypher'

    sco = pymqi.SCO()
    sco.KeyRepository = b'my_location'

    queue_manager = pymqi.QueueManager(None)

    connect_with_options(cd, queue_manager, sco)
    connect_with_options(cd, queue_manager, sco)
    connect_with_options(cd, queue_manager, sco)
    connect_with_options(cd, queue_manager, sco)
    connect_with_options(cd, queue_manager, sco)
    connect_with_options(cd, queue_manager, sco)
    connect_with_options(cd, queue_manager, sco)
    connect_with_options(cd, queue_manager, sco)
    connect_with_options(cd, queue_manager, sco)
    connect_with_options(cd, queue_manager, sco)
    for i in range(100):
        connect_with_options(cd, queue_manager, sco)
    for i in range(1000):
        connect_with_options(cd, queue_manager, sco)


def connect_with_options(cd, queue_manager, sco):
    try:
        queue_manager.connect_with_options("some_qm", cd, sco)
    except Exception:
        pass


profiled_connect()
```

## Memory Profile Results

```
Line #    Mem usage    Increment   Line Contents
================================================
     5  38.3828 MiB  38.3828 MiB   @profile(precision=4)
     6                             def profiled_connect():
     7  38.3828 MiB   0.0000 MiB       cd = pymqi.CD()
     8  38.3828 MiB   0.0000 MiB       cd.ChannelName = b'abc'
     9  38.3828 MiB   0.0000 MiB       cd.ConnectionName = b'abc'
    10  38.3828 MiB   0.0000 MiB       cd.ChannelType = pymqi.CMQC.MQCHT_CLNTCONN
    11  38.3828 MiB   0.0000 MiB       cd.TransportType = pymqi.CMQC.MQXPT_TCP
    12  38.3828 MiB   0.0000 MiB       cd.Version = 6
    13  38.3828 MiB   0.0000 MiB       cd.SSLCipherSpec = b'mycypher'
    14                             
    15  38.3828 MiB   0.0000 MiB       sco = pymqi.SCO()
    16  38.3828 MiB   0.0000 MiB       sco.KeyRepository = b'my_location'
    17                             
    18  38.3828 MiB   0.0000 MiB       queue_manager = pymqi.QueueManager(None)
    19                             
    20  42.5273 MiB   4.1445 MiB       connect_with_options(cd, queue_manager, sco)
    21  42.6328 MiB   0.1055 MiB       connect_with_options(cd, queue_manager, sco)
    22  42.6562 MiB   0.0234 MiB       connect_with_options(cd, queue_manager, sco)
    23  42.6797 MiB   0.0234 MiB       connect_with_options(cd, queue_manager, sco)
    24  42.7344 MiB   0.0547 MiB       connect_with_options(cd, queue_manager, sco)
    25  42.7969 MiB   0.0625 MiB       connect_with_options(cd, queue_manager, sco)
    26  42.8281 MiB   0.0312 MiB       connect_with_options(cd, queue_manager, sco)
    27  42.8555 MiB   0.0273 MiB       connect_with_options(cd, queue_manager, sco)
    28  42.8789 MiB   0.0234 MiB       connect_with_options(cd, queue_manager, sco)
    29  42.9023 MiB   0.0234 MiB       connect_with_options(cd, queue_manager, sco)
    30  45.6328 MiB   0.0000 MiB       for i in range(100):
    31  45.6328 MiB   0.0547 MiB           connect_with_options(cd, queue_manager, sco)
    32  72.3320 MiB   0.0000 MiB       for i in range(1000):
    33  72.3320 MiB   0.0781 MiB           connect_with_options(cd, queue_manager, sco)
```

As you can see, each call to `connect_with_options` will increment the total memory used.

@dsuch Any insight what might be causing this ?

# Platforms

Using the same script shared above. The mem leak happen on:
- OSX with IBM MQ Client 9.1.3.0
- REHL 7.8 with IBM MQ Client 9.1.3.0

It does NOT happen on:
- Ubuntu 16.04 with IBM MQ Client 9.1.3.0

**Comment by JoshMcMQ** [comment] 2020-06-17 14:13
Have you checked the fix list for the version of IBM MQ client in use.   There have been the past client code issues like this, but I can't recall if those are C API or not.

**Comment by AlexandreYang** [comment] 2020-06-17 14:19
The IBM MQ Client I used for the profiling is `9.1.3.0` (added to issue description).

**Comment by dsuch** [comment] 2020-06-17 14:26
Hi @AlexandreYang,

connect_with_options is a fairly thin wrapper around MQCONNX so there is not much room for leaks as far as that method itself goes.

About the only partly unusual thing it does is that it assigns the handle to the queue manager to its .__handle attribute and the connection is only released in the class's ```__del__``` method which, as we know, is not guaranteed to be invoked at any specific time.

All of that was designed and implemented by the PyMQI's original author some 20 years ago and if I remember correctly, he was a C++ programmer as well so perhaps this is what influenced him.

Can you perhaps have a look at "nestat -tulpan" to confirm that you are truly opening a lot of connections?

Also, what if you add a call to .disconnect? Does it mean less RAM used?

For instance:

```
queue_manager.connect_with_options("some_qm", cd, sco)
queue_manager.disconnect()
```

**Comment by dsuch** [comment] 2020-06-17 14:44
Actually, I re-read your original message and you spoke of a memory leak in connect_with_options "when it fails".

But I do not see any failure? I am not sure what you meant by that, can you please clarify?

Thanks.

**Comment by AlexandreYang** [comment] 2020-06-17 15:21
> Also, what if you add a call to .disconnect? Does it mean less RAM used?

If I call `.disconnect`, the error `not connected` will be raised: https://github.com/dsuch/pymqi/blob/84e3d05277717903015d899cfc50345eddf741ef/code/pymqi/__init__.py#L1659

> Can you perhaps have a look at "nestat -tulpan" to confirm that you are truly opening a lot of connections?

Tried, seems not the case.

> But I do not see any failure? I am not sure what you meant by that, can you please clarify?

I just wrapped inside a try/except for the profiling so I can call it multiple time.

```
def connect_with_options(cd, queue_manager, sco):
    try:
        queue_manager.connect_with_options("some_qm", cd, sco)
    except Exception:
        pass
```

**Comment by dsuch** [comment] 2020-06-17 15:52
The only idea that I have is to add a "return" statement in line 1616 to see if it still happens.

Then move the statement to subsequent lines up until the last line in that method to try to pinpoint the place that causes it.

**Comment by dsuch** [comment] 2020-06-17 16:05
I have realised that you are not on the latest version of PyMQI so just to double-confirm it, I meant starting with the line right before MQCONNX is called:

https://github.com/dsuch/pymqi/blob/84e3d05277717903015d899cfc50345eddf741ef/code/pymqi/__init__.py#L1616

**Comment by AlexandreYang** [comment] 2020-06-17 16:27
There is no mem leak if a `return` is placed before `MQCONNX`. `MQCONNX` seems indeed the culprit.

Also, calling ` pymqe.MQDISC` like follow doesn't make mem leak disapear.
```
        rv = pymqe.MQCONNX(name, options, cd, user_password, sco.pack())
        pymqe.MQDISC(rv[0])
        return
```

**Comment by AlexandreYang** [comment] 2020-06-17 16:36
Using the same script shared in description. Looks like the mem leak happen on:
- OSX with IBM MQ Client 9.1.3.0
- And REHL 7.8, but I need to double check that one

It does NOT happen on:
- Ubuntu 16.04 with IBM MQ Client 9.1.3.0

**Comment by JoshMcMQ** [comment] 2020-06-17 16:51
I would check against the latest 9.1.5 CDS and the stable 9.1.0.5 LTS to see if this is still a problem.

**Comment by AlexandreYang** [comment] 2020-06-18 10:12
The leak also happen for RHEL 7.8 with IBM MQ Client 9.1.3.0 (updating the PR desc):

```
[vagrant@rhel7 Python-3.8.3]$ LD_LIBRARY_PATH=/opt/mqm/lib64 python leak.py
Line #    Mem usage    Increment   Line Contents
================================================
     5  17.6719 MiB  17.6719 MiB   @profile(precision=4)
     6                             def profiled_connect():
     7  17.6953 MiB   0.0234 MiB       cd = pymqi.CD()
     8  17.6953 MiB   0.0000 MiB       cd.ChannelName = b'abc'
     9  17.6953 MiB   0.0000 MiB       cd.ConnectionName = b'abc'
    10  17.6953 MiB   0.0000 MiB       cd.ChannelType = pymqi.CMQC.MQCHT_CLNTCONN
    11  17.6953 MiB   0.0000 MiB       cd.TransportType = pymqi.CMQC.MQXPT_TCP
    12  17.6953 MiB   0.0000 MiB       cd.Version = 6
    13  17.6953 MiB   0.0000 MiB       cd.SSLCipherSpec = b'mycypher'
    14
    15  17.6953 MiB   0.0000 MiB       sco = pymqi.SCO()
    16  17.6953 MiB   0.0000 MiB       sco.KeyRepository = b'my_location'
    17
    18  17.6953 MiB   0.0000 MiB       queue_manager = pymqi.QueueManager(None)
    19
    20  23.1367 MiB   5.4414 MiB       connect_with_options(cd, queue_manager, sco)
    21  23.1797 MiB   0.0430 MiB       connect_with_options(cd, queue_manager, sco)
    22  23.2188 MiB   0.0391 MiB       connect_with_options(cd, queue_manager, sco)
    23  23.2539 MiB   0.0352 MiB       connect_with_options(cd, queue_manager, sco)
    24  23.2891 MiB   0.0352 MiB       connect_with_options(cd, queue_manager, sco)
    25  23.3203 MiB   0.0312 MiB       connect_with_options(cd, queue_manager, sco)
    26  23.3516 MiB   0.0312 MiB       connect_with_options(cd, queue_manager, sco)
    27  23.3828 MiB   0.0312 MiB       connect_with_options(cd, queue_manager, sco)
    28  23.4141 MiB   0.0312 MiB       connect_with_options(cd, queue_manager, sco)
    29  23.4453 MiB   0.0312 MiB       connect_with_options(cd, queue_manager, sco)
    30  26.6328 MiB   0.0000 MiB       for i in range(100):
    31  26.6328 MiB   0.0352 MiB           connect_with_options(cd, queue_manager, sco)
    32  58.2539 MiB   0.0000 MiB       for i in range(1000):
    33  58.2539 MiB   0.0430 MiB           connect_with_options(cd, queue_manager, sco)
```

**Comment by dsuch** [comment] 2020-06-18 12:20
Hm, hm, hm.. This is interesting.

If I understand it correctly you have so far checked the case of the queue manager's name being invalid. What if it is in fact a valid one? Does it also happen?

I am also curious to learn how you came up with the idea of testing it out in the first place?

**Comment by AlexandreYang** [comment] 2020-06-18 13:02
The [Datadog `ibm_mq` integration uses `pymqi`](https://github.com/DataDog/integrations-core/blob/ccb6c027ff689d747b76d89ef44e897995937e90/ibm_mq/datadog_checks/ibm_mq/connection.py#L59-L60) for retrieving metrics data. 

The Datadog Agent runner will try to to retrieve to connect/retrieve every 15sec or so. At some point, we had a TLS config that was incorrect, as expected the Datadog Agent continues to try every 15s, leading to memory increase over time (up to 5GB).

**Comment by AlexandreYang** [comment] 2020-06-18 13:26
When the connection is valid, looks like the mem increases, but just slightly.

Results using a slightly modified script:

```
import pymqi
from memory_profiler import profile


@profile(precision=4)
def profiled_connect():

    connect_with_options()
    connect_with_options()
    connect_with_options()
    connect_with_options()
    connect_with_options()
    connect_with_options()
    connect_with_options()
    connect_with_options()
    connect_with_options()
    connect_with_options()
    for _ in range(100):
        connect_with_options()
    for _ in range(1000):
        connect_with_options()

def connect_with_options():
    cd = pymqi.CD()
    cd.ChannelName = b'DEV.ADMIN.SVRCONN'
    cd.ConnectionName = b'localhost(11414)'
    cd.ChannelType = pymqi.CMQC.MQCHT_CLNTCONN
    cd.TransportType = pymqi.CMQC.MQXPT_TCP
    cd.Version = 6
    queue_manager = pymqi.QueueManager(None)

    kwargs = {'user': 'admin', 'password': 'passw0rd', 'cd': cd}
    queue_manager.connect_with_options("datadog", **kwargs)
    queue_manager.disconnect()


profiled_connect()
```

```

Line #    Mem usage    Increment   Line Contents
================================================
     5  13.9922 MiB  13.9922 MiB   @profile(precision=4)
     6                             def profiled_connect():
     7
     8  16.4688 MiB   2.4766 MiB       connect_with_options()
     9  16.5977 MiB   0.1289 MiB       connect_with_options()
    10  16.6484 MiB   0.0508 MiB       connect_with_options()
    11  16.7188 MiB   0.0703 MiB       connect_with_options()
    12  16.7695 MiB   0.0508 MiB       connect_with_options()
    13  16.8125 MiB   0.0430 MiB       connect_with_options()
    14  16.8555 MiB   0.0430 MiB       connect_with_options()
    15  16.8672 MiB   0.0117 MiB       connect_with_options()
    16  16.8828 MiB   0.0156 MiB       connect_with_options()
    17  16.9062 MiB   0.0234 MiB       connect_with_options()
    18  17.1406 MiB   0.0000 MiB       for _ in range(100):
    19  17.1406 MiB   0.0469 MiB           connect_with_options()
    20  17.3164 MiB   0.0000 MiB       for _ in range(1000):
    21  17.3164 MiB   0.0234 MiB           connect_with_options()
```

Here, we end up with 17MiB.

Previously, we end up with 58MiB when connection fail in similar scenario.

**Comment by dsuch** [comment] 2020-06-18 13:35
Thanks a lot for your assistance @AlexandreYang - currently, I do not even have an MQ environment to try it out.

By following the way of elimination, may I ask you to modify pymqe.c and comment out the line that actually calls MQCONNX?

```
MQCONNX(name, &cno, &handle, &comp_code, &comp_reason);
```

This should leave us with a kind of a no-op function that does not call MQ APIs at all.

**Comment by AlexandreYang** [comment] 2020-06-18 14:01
I think the leak is related to the use of `cd.SSLCipherSpec`:

```
Line #    Mem usage    Increment   Line Contents
================================================
     5  14.0820 MiB  14.0820 MiB   @profile(precision=4)
     6                             def profiled_connect():
     7
     8  16.2852 MiB   2.2031 MiB       connect_with_options()
     9  16.3711 MiB   0.0859 MiB       connect_with_options()
    10  16.3750 MiB   0.0039 MiB       connect_with_options()
    11  16.3984 MiB   0.0234 MiB       connect_with_options()
    12  16.4258 MiB   0.0273 MiB       connect_with_options()
    13  16.4297 MiB   0.0039 MiB       connect_with_options()
    14  16.4336 MiB   0.0039 MiB       connect_with_options()
    15  16.4453 MiB   0.0117 MiB       connect_with_options()
    16  16.4453 MiB   0.0000 MiB       connect_with_options()
    17  16.4492 MiB   0.0039 MiB       connect_with_options()
    18  16.7148 MiB   0.0000 MiB       for i in range(100):
    19  16.7109 MiB   0.0078 MiB           print(i)
    20  16.7148 MiB   0.0352 MiB           connect_with_options()
    21  17.4414 MiB   0.0000 MiB       for i in range(1000):
    22  17.4414 MiB   0.0000 MiB           print(i)
    23  17.4414 MiB   0.0273 MiB           connect_with_options()
    24
    25  19.0742 MiB   1.6328 MiB       connect_with_options(cipher=b'mycypher')
    26  19.0898 MiB   0.0156 MiB       connect_with_options(cipher=b'mycypher')
    27  19.1016 MiB   0.0117 MiB       connect_with_options(cipher=b'mycypher')
    28  19.1289 MiB   0.0273 MiB       connect_with_options(cipher=b'mycypher')
    29  19.1445 MiB   0.0156 MiB       connect_with_options(cipher=b'mycypher')
    30  19.1758 MiB   0.0312 MiB       connect_with_options(cipher=b'mycypher')
    31  19.1953 MiB   0.0195 MiB       connect_with_options(cipher=b'mycypher')
    32  19.2422 MiB   0.0469 MiB       connect_with_options(cipher=b'mycypher')
    33  19.2695 MiB   0.0273 MiB       connect_with_options(cipher=b'mycypher')
    34  19.2930 MiB   0.0234 MiB       connect_with_options(cipher=b'mycypher')
    35  21.8672 MiB   0.0000 MiB       for i in range(100):
    36  21.8516 MiB   0.0000 MiB           print(i)
    37  21.8672 MiB   0.0703 MiB           connect_with_options(cipher=b'mycypher')
    38  47.7148 MiB   0.0000 MiB       for i in range(1000):
    39  47.6914 MiB   0.0000 MiB           print(i)
    40  47.7148 MiB   0.0586 MiB           connect_with_options(cipher=b'mycypher')
```


<details><summary>script</summary>


```
import pymqi
from memory_profiler import profile

@profile(precision=4)
def profiled_connect():

    connect_with_options()
    connect_with_options()
    connect_with_options()
    connect_with_options()
    connect_with_options()
    connect_with_options()
    connect_with_options()
    connect_with_options()
    connect_with_options()
    connect_with_options()
    for i in range(100):
        print(i)
        connect_with_options()
    for i in range(1000):
        print(i)
        connect_with_options()

    connect_with_options(cipher=b'mycypher')
    connect_with_options(cipher=b'mycypher')
    connect_with_options(cipher=b'mycypher')
    connect_with_options(cipher=b'mycypher')
    connect_with_options(cipher=b'mycypher')
    connect_with_options(cipher=b'mycypher')
    connect_with_options(cipher=b'mycypher')
    connect_with_options(cipher=b'mycypher')
    connect_with_options(cipher=b'mycypher')
    connect_with_options(cipher=b'mycypher')
    for i in range(100):
        print(i)
        connect_with_options(cipher=b'mycypher')
    for i in range(1000):
        print(i)
        connect_with_options(cipher=b'mycypher')


def connect_with_options(cipher=None):
    cd = pymqi.CD()
    cd.ChannelName = b'abc'
    cd.ConnectionName = b'abc'
    cd.ChannelType = pymqi.CMQC.MQCHT_CLNTCONN
    cd.TransportType = pymqi.CMQC.MQXPT_TCP
    cd.Version = 6
    if cipher:
        cd.SSLCipherSpec = cipher

    queue_manager = pymqi.QueueManager(None)

    try:
        queue_manager.connect_with_options("some_qm", cd)
    except Exception:
        pass


profiled_connect()
```

</details>

**Comment by AlexandreYang** [comment] 2020-06-18 14:06
> By following the way of elimination, may I ask you to modify pymqe.c and comment out the line that actually calls MQCONNX?

When commented out, there is no memory leak.

**Comment by AlexandreYang** [comment] 2020-06-18 14:10
> By following the way of elimination, may I ask you to modify pymqe.c and comment out the line that actually calls MQCONNX?
> MQCONNX(name, &cno, &handle, &comp_code, &comp_reason);

When this line is commented out, there is no leak.

**Comment by AlexandreYang** [comment] 2020-06-18 14:15
So, the issues is likely at IBM MQ Client library level, not in `pymqi`.

**Comment by dsuch** [comment] 2020-06-18 18:44
Thanks. At this point I think the only thing left is to look around in pymqe.c around MQCONNX and try to find what input parameters are causing the issue. 

You said that it seems to be related to TLS so, for instance, commenting out lines to do with MQCD could be a starting point:

```c
  if(mqcd) {
    cno.ClientConnPtr = (MQCD *)mqcd;
  }
```

Unfortunately, I will not have time to do it myself.

**Comment by AlexandreYang** [comment] 2020-06-19 07:42
The leak does not happen when commenting the line you indicated `cno.ClientConnPtr = (MQCD *)mqcd;`.

As mentioned previously, my guess about the input parameter causing the issue is `cd.SSLCipherSpec`. The leak does not happen, when `cd.SSLCipherSpec` is **not** set.

**Comment by dsuch** [comment] 2020-06-19 08:25
Thanks @AlexandreYang - I honestly do not see any issue in PyMQI here in that case and the only thing I can recommend is to contact IBM for assistance. MQ client is not open-source and we are not able to investigate the situation ourselves, unfortunately.

**Comment by AlexandreYang** [comment] 2020-06-19 08:36
Yes, agree with you, the issue seems to be in the IBM MQ Client library.

Do you know how to forward this issue to the right people at IBM ?

Looks like this might be a good starting point: https://community.ibm.com/community/user/imwuc/communities/community-home/digestviewer?communitykey=183ec850-4947-49c8-9a2e-8e7c7fc46c64&tab=digestviewer

I will make a post there.

**Comment by dsuch** [comment] 2020-06-19 08:59
Several people reading our messages are employees of IBM, e.g. @oljarast and @chughts.

**Comment by chughts** [comment] 2020-06-19 09:18
If it is a problem in the C Client library then I would expect to see the problem repeated using Go or Node.js. We should try creating a similar test for one of these languages. 

If it is possible to reproduce the memory leak in Go or Node.js, then we should raise a defect on the Client library. Adding a heads up on the community would be a good idea to raise awareness of these tests.

**Comment by AlexandreYang** [comment] 2020-06-19 10:39
@chughts Just did some simple profiling using `mq-golang` on MacOS with same MQ Client version: 9.1.3.0.

I got the result using `/usr/bin/time -l go run amqsconntls_leak.go` (I'm not that familiar with golang profiling tools, so just used `time -l`).

| LOOPS | RSS WITH cd.SSLCipherSpec | RSS WITHOUT cd.SSLCipherSpec |
|--------|--------------------------|-------------------------------|
| 100 | 59 MB|  59 MB |
| 1000 | 85 MB| 58 MB|
| 2000 | 162 MB| 59 MB|

* RSS: resident set size

Seems to confirm the leak also happen for Go.

Script used: https://gist.github.com/AlexandreYang/deca995ce8d7144a3f4e9b6ea05aaaca

It's modified version of https://github.com/ibm-messaging/mq-golang/blob/master/samples/amqsconntls.go 

<details><summary>`/usr/bin/time -l go run amqsconntls_leak.go` outputs</summary>

```
WITH cd.SSLCipherSpec for 100 loops
        3.94 real         1.30 user         2.16 sys
  59531264  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
     59847  page reclaims
      9365  page faults
         0  swaps
         0  block input operations
         0  block output operations
       901  messages sent
       901  messages received
       327  signals received
      1669  voluntary context switches
     22851  involuntary context switches

WITH cd.SSLCipherSpec for 1000 loops
       34.90 real         9.78 user        21.50 sys
  85712896  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
     79386  page reclaims
       998  page faults
         0  swaps
         0  block input operations
         0  block output operations
      9001  messages sent
      9001  messages received
       634  signals received
      4343  voluntary context switches
     67553  involuntary context switches

WITH cd.SSLCipherSpec for 2000 loops
       68.68 real        19.31 user        42.07 sys
 162439168  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
    102377  page reclaims
      2238  page faults
         0  swaps
         0  block input operations
         0  block output operations
     18001  messages sent
     18001  messages received
      1051  signals received
      8637  voluntary context switches
    134155  involuntary context switches

WITHOUT cd.SSLCipherSpec for 100 loops
        4.39 real         1.62 user         2.25 sys
  59457536  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
     58034  page reclaims
      8899  page faults
         0  swaps
         0  block input operations
         0  block output operations
       901  messages sent
       901  messages received
       343  signals received
      1917  voluntary context switches
     24925  involuntary context switches

WITHOUT cd.SSLCipherSpec for 1000 loops
       39.13 real        13.33 user        21.77 sys
  58535936  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
     58319  page reclaims
      8885  page faults
         0  swaps
         0  block input operations
         0  block output operations
      9001  messages sent
      9001  messages received
       745  signals received
      5315  voluntary context switches
     89245  involuntary context switches

WITHOUT cd.SSLCipherSpec for 2000 loops
       76.38 real        26.19 user        42.40 sys
  59633664  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
     60289  page reclaims
      7738  page faults
         0  swaps
         0  block input operations
         0  block output operations
     18001  messages sent
     18001  messages received
      1243  signals received
      9405  voluntary context switches
    159700  involuntary context switches

```
</details>

**Comment by AlexandreYang** [comment] 2020-06-25 13:24
Also posted to [IBM Community - Memory leak on connection (MQCONNX) failure when `cd.SSLCipherSpec` is used](https://community.ibm.com/community/user/imwuc/communities/community-home/digestviewer/viewthread?MessageKey=66b63837-96ec-4e33-812b-2d1257111483&CommunityKey=183ec850-4947-49c8-9a2e-8e7c7fc46c64&tab=digestviewer#bm66b63837-96ec-4e33-812b-2d1257111483)

**Comment by SeyfSV** [comment] 2020-06-26 06:59
Let's close this issue

**Comment by AlexandreYang** [comment] 2020-06-26 07:23
@SeyfSV Yes, make sense to close this ticket since the issue is at Client library level.

> If it is possible to reproduce the memory leak in Go or Node.js, then we should raise a defect on the Client library. Adding a heads up on the community would be a good idea to raise awareness of these tests.

@chughts Do you know how/where we can raise a defect on the Client library ?

**Comment by Skyler-Altol** [comment] 2020-06-28 10:16
@AlexandreYang I may be able to be of service here. Since one of my projects at work is now going to be leveraging PyMQI, and we have numerous IBM Vendor contractors working with us, I can request a PMR be raised based on this github issue, since it's possible it could affect what I'm working on. I'll ask and report back with what happens.

**Comment by dsuch** [comment] 2020-06-28 11:04
Hi @Skyler-Altol - yes, please open a PMR pointing to this ticket, that will be helpful. Thanks.

**Comment by Skyler-Altol** [comment] 2020-06-28 23:44
@AlexandreYang can you please repeat these tests with MQ Client 9.1.5? Our Vendor is requesting to try this before raising a PMR.

**Comment by AlexandreYang** [comment] 2020-07-01 08:23
@Skyler-Altol Thanks a lot for your help. The same leak is present on MQ Client 9.1.5. Here are the results:

I'm using [9.1.5.0-IBM-MQ-Toolkit-MacX64.tar.gz](https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqdev/mactoolkit/9.1.5.0-IBM-MQ-Toolkit-MacX64.tar.gz)

```
Line #    Mem usage    Increment   Line Contents
================================================
     5  14.1641 MiB  14.1641 MiB   @profile(precision=4)
     6                             def profiled_connect():
     7  14.1680 MiB   0.0039 MiB       cd = pymqi.CD()
     8  14.1680 MiB   0.0000 MiB       cd.ChannelName = b'abc'
     9  14.1680 MiB   0.0000 MiB       cd.ConnectionName = b'abc'
    10  14.1680 MiB   0.0000 MiB       cd.ChannelType = pymqi.CMQC.MQCHT_CLNTCONN
    11  14.1680 MiB   0.0000 MiB       cd.TransportType = pymqi.CMQC.MQXPT_TCP
    12  14.1680 MiB   0.0000 MiB       cd.Version = 6
    13  14.1680 MiB   0.0000 MiB       cd.SSLCipherSpec = b'mycypher'
    14
    15  14.1680 MiB   0.0000 MiB       sco = pymqi.SCO()
    16  14.1680 MiB   0.0000 MiB       sco.KeyRepository = b'my_location'
    17
    18  14.1680 MiB   0.0000 MiB       queue_manager = pymqi.QueueManager(None)
    19
    20  18.6172 MiB   4.4492 MiB       connect_with_options(cd, queue_manager, sco)
    21  18.7500 MiB   0.1328 MiB       connect_with_options(cd, queue_manager, sco)
    22  18.8672 MiB   0.1172 MiB       connect_with_options(cd, queue_manager, sco)
    23  18.9844 MiB   0.1172 MiB       connect_with_options(cd, queue_manager, sco)
    24  19.0547 MiB   0.0703 MiB       connect_with_options(cd, queue_manager, sco)
    25  19.1992 MiB   0.1445 MiB       connect_with_options(cd, queue_manager, sco)
    26  19.2734 MiB   0.0742 MiB       connect_with_options(cd, queue_manager, sco)
    27  19.2812 MiB   0.0078 MiB       connect_with_options(cd, queue_manager, sco)
    28  19.3906 MiB   0.1094 MiB       connect_with_options(cd, queue_manager, sco)
    29  19.4375 MiB   0.0469 MiB       connect_with_options(cd, queue_manager, sco)
    30  23.1055 MiB   0.0000 MiB       for i in range(50):
    31  23.1055 MiB   0.1250 MiB           connect_with_options(cd, queue_manager, sco)
    32  95.2656 MiB   0.0000 MiB       for i in range(1000):
    33  95.2656 MiB   0.1602 MiB           connect_with_options(cd, queue_manager, sco)
```

**Comment by Skyler-Altol** [comment] 2020-07-01 09:03
I will need to re-run the RHEL tests on our internal systems (because otherwise they won't raise it). But I can handle that, Thanks for repeating the mac tests, that was the one OS that I couldn't test myself. RHEL is easy. Will let you know once it's raised and sorted. Might take some time as I'm currently ill and not going to work, but when I'm back I'll get it raised and hopefully dealt with in a later client version. (or fixpack for the LTS releases).

**Comment by dsuch** [comment] 2020-07-01 09:16
@chughts @oljarast Have you forwarded this ticket to your colleagues in the development?

It seems that there is a rather clear memory leak confirmed in Python and Go wrappers, do @Skyler-Altol and @AlexandreYang really need to spend more of their free time on this?

**Comment by chughts** [comment] 2020-07-01 09:23
We have, but a defect from an external source will carry more weight.

**Comment by dsuch** [comment] 2020-07-01 09:25
Right, thanks.

**Comment by SeyfSV** [comment] 2020-10-31 17:10
Let's close this issue. We can't fix it :(, we can only wait and hope :)

**Closed by SeyfSV** 2020-10-31 17:10 UTC
Labels: question

**Comment by yzhan289** [comment] 2022-01-20 17:19
Hi @chughts and @oljarast , just wondering the progress on this ticket.

**Comment by chughts** [comment] 2022-01-21 09:29
Since you managed to reproduce with go, I suggest raising the issue on this repo - https://github.com/ibm-messaging/mq-golang
