### ISSUE TITLE
Stats messages are incomprehensible

### ISSUE THREAD

**Issue by gmmeyer** [dsuch/pymqi#75] opened 2018-09-04 20:17 UTC
I'm working on getting stats out of pymqi. I've subscribed to the stats endpoint, but the messages I'm getting look like this:

```
\x16\x00\x00\x00$\x00\x00\x00\x03\x00\x00\x00\xa7\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00<\x00\x00\x00\x04\x00\x00\x00D\x00\x00\x00\xdf\x07\x00\x00\x00\x00\x00\x000\x00\x00\x00datadog                                         \x04\x00\x00\x00 \x00\x00\x00\x97\n\x00\x00\x00\x00\x00\x00\n\x00\x00\x002018-09-04  \x04\x00\x00\x00\x1c\x00\x00\x00\x98\n\x00\x00\x00\x00\x00\x00\x08\x00\x00\x0019.07.31\x04\x00\x00\x00 \x00\x00\x00\x93\n\x00\x00\x00\x00\x00\x00\n\x00\x00\x002018-09-04# \x04\x00\x00\x00\x1c\x00\x00\x00\x94\n\x00\x00\x00\x00\x00\x00\x08\x00\x00\x0019.23.13\x03\x00\x00\x00\x10\x00\x00\x00\x1f\x00\x00\x00\x89\x03\x00\x00\t\x00\x00\x00(\x00\x00\x00^\x1b\x00\x00\x18\x00\x00\x00AMQCdatadog     \xce\xcc\x8e[\x07"\xc6%\x03\x00\x00\x00\x10\x00\x00\x007\x04\x00\x00\x00\x00\x00\x00\x04\x00\x00\x000\x00\x00\x00\xd0\x0b\x00\x00\x00\x00\x00\x00\x1c\x00\x00\x00python                      \x03\x00\x00\x00\x10\x00\x00\x00\x00\x04\x00\x00\xbf\x01\x00\x00\x03\x00\x00\x00\x10\x00\x00\x00\x01\x04\x00\x00 \x00\x00\x00\x04\x00\x00\x00 \x00\x00\x00\xd1\x0b\x00\x00\x00\x00\x00\x00\x0c\x00\x00\x00admin       \x04\x00\x00\x00 \x00\x00\x00\x8f\n\x00\x00\x00\x00\x00\x00\n\x00\x00\x002018-09-04 v\x04\x00\x00\x00\x1c\x00\x00\x00\x90\n\x00\x00\x00\x00\x00\x00\x08\x00\x00\x0019.07.31\x04\x00\x00\x00\x1c\x01\x00\x00\xb2\r\x00\x00\x00\x00\x00\x00\x08\x01\x00\x00172.17.0.1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00(\x00\x00\x00\xad\r\x00\x00\x00\x00\x00\x00\x14\x00\x00\x00DEV.ADMIN.SVRCONN   \x04\x00\x00\x00 \x00\x00\x00\x91\n\x00\x00\x00\x00\x00\x00\n\x00\x00\x002018-09-04\x00\x00\x04\x00\x00\x00\x1c\x00\x00\x00\x92\n\x00\x00\x00\x00\x00\x00\x08\x00\x00\x0019.23.13\x03\x00\x00\x00\x10\x00\x00\x00\xcc\x02\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00D\x00\x00\x00\xdd\x02\x00\x00\r\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00D\x00\x00\x00\xef\x02\x00\x00\r\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00D\x00\x00\x00\xc5\x02\x00\x00\r\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00D\x00\x00\x00\xf5\x02\x00\x00\r\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x18\x00\x00\x00\xdf\x02\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x10\x00\x00\x00\xf2\x02\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x18\x00\x00\x00\xde\x02\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x10\x00\x00\x00\xf3\x02\x00\x00\x00\x00\x00\x00\x19\x00\x00\x00 \x00\x00\x00\xec\x02\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x18\x00\x00\x00\xd2\x02\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x10\x00\x00\x00\xd5\x02\x00\x00\xa4\xfd\x13\x00\x19\x00\x00\x00 \x00\x00\x00\xeb\x02\x00\x00\x02\x00\x00\x00L\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x18\x00\x00\x00\xc1\x02\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x10\x00\x00\x00\xc4\x02\x00\x00\x00\x00\x00\x00\x19\x00\x00\x00 \x00\x00\x00\xe9\x02\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x10\x00\x00\x00\xc6\x02\x00\x00\x01\x00\x00\x00\x03\x00\x00\x00\x10\x00\x00\x00\xc7\x02\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x10\x00\x00\x00\xc0\x02\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00D\x00\x00\x00\xd7\x02\x00\x00\r\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00D\x00\x00\x00\xf0\x02\x00\x00\r\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00D\x00\x00\x00\xe8\x02\x00\x00\r\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00D\x00\x00\x00\xf1\x02\x00\x00\r\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x1c\x00\x00\x00\xfc\x02\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x1c\x00\x00\x00\xfd\x02\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x10\x00\x00\x00\xfe\x02\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x18\x00\x00\x00\x12\x03\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x18\x00\x00\x00\x13\x03\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x10\x00\x00\x00\x14\x03\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x10\x00\x00\x00\xff\x02\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x10\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00 \x00\x00\x00\x01\x03\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x10\x00\x00\x00\x02\x03\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00 \x00\x00\x00\x03\x03\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x10\x00\x00\x00\x04\x03\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x10\x00\x00\x00\x05\x03\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x10\x00\x00\x00\x06\x03\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x18\x00\x00\x00\x0b\x03\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x10\x00\x00\x00\x0c\x03\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x18\x00\x00\x00\r\x03\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x10\x00\x00\x00\x0e\x03\x00\x00\x00\x00\x00\x00\x19\x00\x00\x00 \x00\x00\x00\x0f\x03\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
```

I can't find anything in your docs or code that might parse this, though I might have missed something. Do you know why this might be happening?

**Comment by dsuch** [comment] 2018-09-05 16:43
Can you tell me what exactly you subscribed to, what format of messages you were expecting instead of this one and what IBM documentation has to say about it?

**Comment by gmmeyer** [comment] 2018-09-10 15:51
I was subscribing to statistics. I can't find good docs on how to parse it, which is part of why I posted this here. The queue is: "SYSTEM.ADMIN.STATISTICS.QUEUE"

**Comment by JoshMcMQ** [comment] 2018-09-12 00:07
The messages are in a PCF format.  There are many examples in the pymqi examples folder that show you to send commands to the command server and process the PCF response from the command server for example [dis_queues.py](https://github.com/dsuch/pymqi/blob/master/code/examples/dis_queues.py), the problem is that it appears that the act of sending something to the command server results in a return of a structure that has interpreted the PCF response.  I'm not sure if there is a pymqi function that you can call separately to process a message you know is in a PCF format.

**Comment by gmmeyer** [comment] 2018-09-13 14:57
@JoshMcMQ how do I decode PCF format?

**Comment by JoshMcMQ** [comment] 2018-09-15 20:32
@gmmeyer you can look at the c sample `amqsevt.c` that comes with MQ v8 and higher full client install to see how it is done in C.  It is not my area of expertise (I'm a MQ admin not a developer) but I was trying to help point you in the right direction.

**Comment by gmmeyer** [comment] 2018-09-17 17:13
The MQAI does use PCF format (making it more confusing to me what PCF is it a protocol or more?). Thanks for the help, I'll work more on this.

**Comment by JoshMcMQ** [comment] 2018-09-17 20:27
PCF is Programmable Change Format.  Originally this was used for sending commands to MQ's command server and receiving responses from the command server.  In this case you are just putting a message that has the right format field set with a command in the PCF format to the command server and the responses that the command server replies with are also in the PCF format.

In the case of statistics, you are only receiving messages that MQ is publishing, they are also in this PCF format.

Google presentations by Mark Taylor related to amqsevt and in general PCF for more details.  Check out https://www.mqtechconference.com/, under sessions at the bottom of the page you can access the full session presentations from past years, Mark and others have presented on PCF in the past.

**Comment by gmmeyer** [comment] 2018-09-18 17:33
@JoshMcMQ Thanks!

**Comment by JoshMcMQ** [comment] 2018-11-02 00:42
@gmmeyer FYI I noticed that Matthew Whitehead from IBM MQ development posted a blog describing how to get pymqi to parse the JSON output of the `amqsevt` program which itself can convert the PCF messages (for instance on the SYSTEM.ADMIN.STATISTICS.QUEUE) to JSON format.  This may not be the best method to achieve what you want but I did want to pass it on.

[Parsing MQ event messages as Python objects using amqsevt](https://developer.ibm.com/messaging/2018/10/31/parsing-mq-event-messages-as-python-objects-using-amqsevt/)

**Comment by dsuch** [comment] 2019-01-03 19:57
Thanks everyone for the participation, I am closing the ticket.

**Closed by dsuch** 2019-01-03 19:57 UTC

**Comment by AlexandreYang** [comment] 2020-06-18 10:18
Fixed by https://github.com/dsuch/pymqi/pull/202 and https://github.com/dsuch/pymqi/commit/ffebfeaed521c46c1720f09f2300262a3f049c34
