### ISSUE TITLE
Topic is always empty - Reason 2033: FAILED: MQRC_NO_MSG_AVAILABLE

### ISSUE THREAD

**Issue by smc87** [dsuch/pymqi#234] opened 2020-10-28 23:31 UTC
I am using pymqi to connect to a queue manager and query for all messageflow statistics topics using the topic string: $SYS/Broker/+/StatisticsAccounting/Archive/#

When using the existing java program messages are read from the topic without issue. When using the new pymqi code it is able to connect and query the topic without issue but always gives this message:
`
Reason 2033: FAILED: MQRC_NO_MSG_AVAILABLE
`
Stats messages are published by the broker for each messageflow every 10 minutes, and I have left the new code running for over 30minutes, never having received a message.
I've also tried setting
`get_opts['WaitInterval'] = pymqi.CMQC.MQWI_UNLIMITED` 
and sitting around for 20minutes rather than using a loop, but no luck.

Is there any IIB server config that might be impacting the messages that I am able to see, or are there other options I should be using within the client?

```
import pymqi

queue_manager = 'MYQM'
channel = 'MYAPP.SVRCONN'
host = 'MYHOST'
port = 'MYPORT'
topic_string = '$SYS/Broker/+/StatisticsAccounting/Archive/#'
conn_info = '%s(%s)' % (host, port)
user = ""
password = ""

qmgr = pymqi.QueueManager(None)
qmgr.connect_tcp_client(queue_manager, pymqi.CD(), channel, conn_info, user, password)
sub_desc = pymqi.SD()
sub_desc['Options'] = pymqi.CMQC.MQSO_CREATE + pymqi.CMQC.MQSO_RESUME + pymqi.CMQC.MQSO_MANAGED
sub_desc.set_vs('SubName', 'apptest')
sub_desc.set_vs('ObjectString', topic_string)
sub = pymqi.Subscription(qmgr)
sub.sub(sub_desc=sub_desc)
get_opts = pymqi.GMO(Options=pymqi.CMQC.MQGMO_WAIT)
get_opts['WaitInterval'] = 10000

md = pymqi.md()
keep_running = True
while keep_running:
    try:
        # Reset the MsgId, CorrelId & GroupId so that we can reuse
        # the same 'md' object again.
        md.MsgId = pymqi.CMQC.MQMI_NONE
        md.CorrelId = pymqi.CMQC.MQCI_NONE
        md.GroupId = pymqi.CMQC.MQGI_NONE

        message = sub.get(None, md, get_opts)
        print('Have message from Queue')
        print(message)

    except pymqi.MQMIError as e:
        if e.comp == pymqi.CMQC.MQCC_FAILED and e.reason == pymqi.CMQC.MQRC_NO_MSG_AVAILABLE:
            print("no message?")
            print(e)
            pass
        else:
            # Some other error condition.
            raise

    except (UnicodeDecodeError, ValueError)  as e:
        print('Message is not valid json')
        print(e)
        print(message)
        continue

    except KeyboardInterrupt:
        print('Have received a keyboard interrupt')
        keep_running = False


sub.close(sub_close_options=0,close_sub_queue=True)
qmgr.disconnect()
```

**Comment by JoshMcMQ** [comment] 2020-10-29 02:00
Do you have access to the queue manager?  Which version of MQ does it run?  Which version of MQ client are you using with pymqi?

**Comment by smc87** [comment] 2020-10-29 09:06
I dont have direct access to the queue manager, but I can speak to the people who do.
I am using MQ client 9.0.5 and the server is on 9.0.0.1

**Comment by chughts** [comment] 2020-10-29 10:20
If you can get a java subscribe working then it's likely that the server is configured correctly. Most likely the issue is in the python code. 

I am assuming that the credentials and server that your python app is using are the same that your java app is using. 

If you python code can connect, then I am thinking along the lines that your topic string `'$SYS/Broker/+/StatisticsAccounting/Archive/#'`isn't being interpreted correctly. Is that the same string that your Java program is using? If it is then may be you need to add a version to `pymqi.CD()`. Out of habit I use `pymqi.CD(Version=pymqi.CMQXC.MQCD_VERSION_11)`

The other difference between your code, and the samples is that the samples tend to also or in the option
`pymqi.CMQC.MQSO_DURABLE`

**Comment by smc87** [comment] 2020-10-29 13:16
when running this command against the queue manager i am able to see that messages do exist:
DISPLAY TPSTATUS('$SYS/Broker/+/StatisticsAccounting/Archive/#') TYPE(SUB) ALL

```
AMQ8754: Display topic status details.
   TOPICSTR($SYS/Broker/BROKERNAME/StatisticsAccounting/Archive/SUPC_Internal/flowName)
   SUBID(414D5120564D51494E535431202020205F6F4490287598D0)
   SUBUSER(itmagent)                       RESMDATE(2020-10-19)
   RESMTIME(09:45:24)                      LMSGDATE(2020-10-29)
   LMSGTIME(12:04:18)
   ACTCONN(000000000000000000000000000000000000000000000000)
   DURABLE(NO)                             SUBTYPE(API)
   MCASTREL( , )                           NUMMSGS(2273624)
AMQ8754: Display topic status details.
   TOPICSTR($SYS/Broker/BROKERNAME/StatisticsAccounting/Archive/MDAT/flowName)
   SUBID(414D5120564D51494E535431202020205F93801F22A56B09)
   SUBUSER(mqtest)                         RESMDATE(2020-10-29)
   RESMTIME(11:23:30)                      LMSGDATE( )
   LMSGTIME( )
   ACTCONN(414D5143564D51494E535431202020205F93801F22A56B06)
   DURABLE(NO)                             SUBTYPE(API)
   MCASTREL( , )                           NUMMSGS(0)
```

I had a similar thought about the string. The string being used is exactly the same as in the java program. I'm not sure if there is some low level transformation done on the string somewhere though that might be different between java and python. 

I tried adding pymqi.CMQC.MQSO_DURABLE to the sub_desc['Options']
When running the code after doing this i get the following error:
```
Reason 2522: FAILED: MQRC_INVALID_DESTINATION
``` 

I tried adding 
```
cd = pymqi.CD(Version=pymqi.CMQXC.MQCD_VERSION_9) 
```
however this just gave the same MQRC_NO_MSG_AVAILABLE

**Comment by dsuch** [comment] 2020-10-29 13:21
I am not aware of any string transformation taking place - had there been one there would have been likely an MQ error raised along the lines of 'Unknown topic name on input'.

But just to be completely on the safe side, can you please use a raw string as the topic's name, i.e. prefix it with an 'r', like below?

```python
topic_string = r'$SYS/Broker/+/StatisticsAccounting/Archive/#'
```

**Comment by dsuch** [comment] 2020-10-29 13:23
Also, please post your Python version - ```python -c "import sys; print(sys.version)"```.

**Comment by smc87** [comment] 2020-10-29 14:08
3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]

using the raw astring I continue to get the message:
Reason 2033: FAILED: MQRC_NO_MSG_AVAILABLE

**Comment by dsuch** [comment] 2020-10-29 14:14
I am not sure what the equivalent MQSC command would be for topics but here is an idea.

With queues, one can check processes which have a given queue open for input or output (IPROCS and OPROCS) - can the same be done with topics?

For instance, you connect and open a topic, then wait 180 seconds (gmo.WaitInterval). In that time, you check the topic's IPROCS and OPROCS, assuming that a relevant command exists for topics, I do not know myself if it does.

In this way you would at least confirm that you access the correct topic.

**Comment by smc87** [comment] 2020-10-29 17:18
I spoke to our MQ admin and he was able to see the subscription with the below details:

appTest
Topic string = $SYS/Broker/+/StatisticsAccounting/Archive/#
Topic name is blank 
Dest is SYSTEM.MANAGED.NDURABLE.<id>

Which to me seems to confirm the topic string is getting passed without any issue.

**Comment by dsuch** [comment] 2020-10-29 19:01
Can the administrator provide the output from MQSC instead of a description? E.g. what is the difference between a topic string and topic name?

I do not know how to proceed myself but perhaps the information will be useful for someone else.

**Comment by SeyfSV** [comment] 2020-10-29 20:58
Hi @smc87,
I checked your sample with python 3.7.5 and 3.8.5 - in both cases it works perfectly.
I changed `topic_string` to `/test/+/test/#` and published some messages from MQ Explorer to topic strings `/test/a/test/b` and `/test/a/test/b/b'.

What I think:
# You create non-durable subscription (you wrote early and show SYSTEM.MANAGED.NDURABLE.<id> queue) it does not have any messages, as result you got 2033. You should wait some time for new messages.
# I adde pymqi.CMQC.MQSO_DURABLE to sub_desc['Options']:
```
sub_desc['Options'] = pymqi.CMQC.MQSO_CREATE + pymqi.CMQC.MQSO_RESUME + pymqi.CMQC.MQSO_MANAGED + pymqi.CMQC.MQSO_DURABLE
```
it works perfectly. I published some messages before starting code, started code, received messages.

**Comment by smc87** [comment] 2020-10-29 21:07
Thanks for testing @SeyfSV 
I tried using the same sub_desc as you but got
```
 Reason 2522: FAILED: MQRC_INVALID_DESTINATION
```
I'm at a total loss here too honestly. I know the messages are there but just can't seem to get at them. 
I'll talk more to our MQ guys tomorrow.

**Comment by JoshMcMQ** [comment] 2020-10-30 02:14
I have a few observations.

The durable perm dynamic queue or non-durable temp dynamic queue is created based on the dynamic queue names listed in the `MDURMDL` and `MNDURMDL` attributes of the topic object which is closest in the tree to your topic string.   I commonly set these to the word `DISABLED` which is not a valid queue name and it would cause the app to get MQRC 2522 when attempting a managed subscription.  This is only used if you do not open and pass in a normal queue name (a provided subscription).

You list two topic status entries, the first is a sub from user `itmagent` which is likely the QI agent for monitoring IIB/ACE, this shows messages published,  the second is likely your python app and it shows 0 messages published.

**Comment by smc87** [comment] 2020-10-30 10:30
Thanks Josh, you are right.

Looking closer at the debug messages, every entry that has a SUBUSER that matches what is defined in sub_desc.set_vs('SubName', 'apptest') shows no messages:

AMQ8754: Display topic status details.
   TOPICSTR($SYS/Broker/BROKERNAME/StatisticsAccounting/Archive/SUPC/FLOWNAME)
   SUBID(414D5120564D51494E535431202020205F93801F222E5819)
   SUBUSER(apptest)                         RESMDATE(2020-10-28)
   RESMTIME(15:16:09)                      LMSGDATE( )
   LMSGTIME( )
   ACTCONN(000000000000000000000000000000000000000000000000)
   DURABLE(YES)                            SUBTYPE(API)
   MCASTREL( , )                           NUMMSGS(0)

Where NUMMSGS is not 0, the SUBUSER is always from a different application. 

I'm not sure what that suggests.

**Comment by SeyfSV** [comment] 2020-10-31 14:56
@smc87 ,  NUMMSGS - is not message count in "queue".
> NUMMSGS
    The number of messages put to the destination specified by this subscription since it was created, or since the queue manager was restarted, whichever is more recent. This number might not reflect the total number of messages that are, or have been, available to the consuming application. This is because it might also include publications that were partially processed but then undone by the queue manager due to a publication failure, or publications that were made within syncpoint that were rolled-back by the publishing application.

Just run your program and wait for messages :) 
Or if you want to use durable subscription (to receive messages published when program was not run), than ask your admin to fix topic definition, or ask him to provide you dedicated queue for message, that you can use in subscription.

**Comment by SeyfSV** [comment] 2020-11-01 15:45
@smc87 , I will close this issue as it is not related to pymqi.
Additional info https://stackoverflow.com/questions/64580523/ibm-stats-subscription-topic-always-returns-reason-2033-failed-mqrc-no-msg-ava

**Closed by SeyfSV** 2020-11-01 15:45 UTC
Labels: question
