### ISSUE TITLE
Randomly receiving MQ error Reason 2058

### ISSUE THREAD

**Issue by Edgarkaz** [dsuch/pymqi#117] opened 2019-06-13 05:53 UTC
Hello,

I have a working python script that implements pymqi to inquiry our MQ queue depth and other related information.
The issue is that we're receiving below error randomly on every 5-6 run,  what could be the reason for a such behaviour? 

 	[Traceback (most recent call last): 
File "/usr/local/nagios_plugins/check_mq_queue.py", line 37, in <module>
qmgrconnection = pymqi.connect(Queue_manager, channel, conn_info, user, password)
File "/usr/lib64/python2.7/site-packages/pymqi/__init__.py", line 2617, in connect
qmgr.connect_tcp_client(queue_manager or '', CD(), channel, conn_info, user, password)
File "/usr/lib64/python2.7/site-packages/pymqi/__init__.py", line 1450, in connect_tcp_client
self.connect_with_options(name, cd, user=user, password=password)
File "/usr/lib64/python2.7/site-packages/pymqi/__init__.py", line 1432, in connect_with_options
raise MQMIError(rv[1], rv[2])
pymqi.MQMIError: MQI Error. Comp: 2, Reason 2058: FAILED: MQRC_Q_MGR_NAME_ERROR]

My env: 
Amazon Linux 2
Python 2.7.14

Output: python -c 'import pymqi; print(pymqi.__mqbuild__)'
client

**Comment by dsuch** [comment] 2019-06-13 11:12
Hi @Edgarkaz - you need to provide a short self-contained usage example that exhibits the behaviour, otherwise it is practically impossible to say what your code may be doing. Thanks.

**Comment by Edgarkaz** [comment] 2019-06-13 11:19
thanks for the quick response, below is an example of the connection 

`channel ="xxxx"
host = "xxxx"
conn_info = "%s(%s)" % (host, port)
user = 'xxxxx'
password = 'xxxxxx'

try:
    qmgrconnection = pymqi.connect(Queue_manager, channel, conn_info, user, password)
except pymqi.MQMIError, e:
        prints
		
queue = pymqi.Queue(Queue_manager,Queue_name)
queue_type = pymqi.CMQC.MQQT_LOCAL


args = {pymqi.CMQC.MQCA_Q_NAME: Queue_name,
        pymqi.CMQC.MQIA_Q_TYPE: queue_type}

pcf = pymqi.PCFExecute(qmgrconnection)

try:
    response = pcf.MQCMD_INQUIRE_Q(args)
except pymqi.MQMIError, e:
    if e.comp == pymqi.CMQC.MQCC_FAILED and e.reason == pymqi.CMQC.MQRC_UNKNOWN_OBJECT_NAME:
       print
	   sys.exit(3)
    else:
       print
        sys.exit(2)
else:
    for queue_info in response:
        	   
	   ##### internal code

qmgrconnection.disconnect()`

**Comment by dsuch** [comment] 2019-06-13 11:24
This is not a self-contained piece of code so I cannot execute it but I assume that variables such as 'Queue_manager' or 'Queue_name' are defined elsewhere in your program.

If that be the case, and 'Queue_manager' actually points to the expected queue manager then I see nothing wrong with this code, it is correct and the issue is elsewhere, not in the usage of PyMQI.

I suggest to look MQRC 2058 in MQ docs and analyze your environment, asking if there is no external factor involved. That is, again, I assume that the 'Queue_manager' variable is correctly defined.

**Comment by Edgarkaz** [comment] 2019-06-13 11:32
Thank you, 
yes these variables are defined at the beginning of the script,
 thank you for the input, we will investigate the MQ infrastructure.

**Comment by dsuch** [comment] 2019-06-13 11:58
When you find the root cause, please share it here because it may be useful to other users in the future. Thanks again.

**Comment by JoshMcMQ** [comment] 2019-07-18 20:44
Does the host and port in your example point directly to a queue manager or is it a VIP on some device like a load balancer?  The error 2058 if you actually connect to a queue manager listener means that the queue manager name you specified does not match the name of the queue manager you connected to.  You mention it happens intermittently, so maybe you have load balancer VIP that is sending you to the wrong queue manager?  The other cause of 2058 is if you don't specify hostname and port number MQ libraries will look for connection information some other locations (ex: env variable `MQSERVER` or in a CCDT found via env variables `MQCHLLIB`/`MQCHLTAB` or equivalent to these in the `mqclient.ini`).  If MQ can't find details of how to connect to a given queue manager name it will also return 2058.  You can normally gain some additional information from `/var/mqm/errors/AMQERR01.LOG`.

**Comment by JoshMcMQ** [comment] 2019-12-09 21:36
Closing because of lack of further feedback.

**Closed by JoshMcMQ** 2019-12-09 21:36 UTC
