### ISSUE TITLE
pymqi.MQMIError: MQI Error. Comp: 2, Reason 2539: FAILED: MQRC_CHANNEL_CONFIG_ERROR

### ISSUE THREAD

**Issue by pycon01** [dsuch/pymqi#107] opened 2019-04-18 22:02 UTC
Im getting the following error while connecting IBM MQ using  PYMQI package
pymqi.MQMIError: MQI Error. Comp: 2, Reason 2539: FAILED: MQRC_CHANNEL_CONFIG_ERROR

iibmmq:8.0
pymqi version: 1.8.0
Python Version: 3.7.0
MQI Levels: ('5.0', '5.1', '5.2', '5.3', '6.0', '7.0', '7.1', '7.5', '8.0.0', '8.0.1')

Its SVRCONN MQ Channel
I'm trying to connect thru SSL and above error is throwing. 
Key repository = key.kdb

sco = pymqi.sco(KeyRepository = key_repo_location)
qmgr = pymqi.QueueManager(None)
qmgr.connectWithOptions(queue_manager, cd, sco)

Error mesg:
pymqi\__init__.py", line 1429, in connect_with_options
    raise MQMIError(rv[1], rv[2])
pymqi.MQMIError: MQI Error. Comp: 2, Reason 2539: FAILED: MQRC_CHANNEL_CONFIG_ERROR

Any help would be appreciated.

**Comment by dsuch** [comment] 2019-04-19 09:41
Hello @pycon01,

MQRC 2539 means a channel configuration error. Per documentation:

https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.0.0/com.ibm.mq.tro.doc/q045390_.htm

"Examine the queue manager and client error logs for messages explaining the cause of the problem. "

There are people here more knowledgeable in MQ administration than I am but the first thing to do is to carry out the steps from MQ documentation, as above.

Thank you.

**Comment by JoshMcMQ** [comment] 2019-04-19 09:56
@pycon01 what value do you have for `key_repo_location`.  In the context of MQ this should be the "stub" of the key repository.

For example you stated the key repository was called `key.kdb`, in reality there are a set of files which contain at a minimum the following, the first being the key repository db and the second the "stash" file that old a IBM MQ obfuscated version of the password to allow MQ to access the `key.kdb`:

```
key.kdb
key.sth
```

The value of `KeyRepository` should be simply `key` if it was in the same directory as the program you run, if not it should specify the path as well like `/tmp/key`.   MQ will know to look for `key.kdb` and `key.sth` in the location specified.

**Comment by pycon01** [comment] 2019-04-19 14:54
@JoshMcMQ  The key repository have following files:
key.kdb
key.rdb
key.sth

the path specified as below
/tmp/keystore/key

we converted these key from jks to cms using Ikeyman(IBM Utility)

**Comment by JoshMcMQ** [comment] 2019-04-22 20:07
Have you checked that the channel name specified in the `cd` is defined on the queue manager as a `SVRCONN` channel?  See my issue #93 and see if this helps at all.  If not I'll suggest some more troubleshooting steps.

**Comment by chughts** [comment] 2019-04-23 15:24
What do the MQ server side logs show? Use the cheat sheet - section 3 & 4 to guide you to the logs - https://developer.ibm.com/messaging/learn-mq/mq-tutorials/dev-cheat-sheet/

Generally a 2539 seems to indicate a mismatch in the client and server channel specification. Are you specifying a CipherSpec ? ie. in your code - 


`cd.SSLCipherSpec = ...`

**Comment by JoshMcMQ** [comment] 2019-12-10 10:13
No updates, closing issue.

**Closed by JoshMcMQ** 2019-12-10 10:13 UTC
