### ISSUE TITLE
need help with connecting to queue manager from python

### ISSUE THREAD

**Issue by mrkksparrow** [dsuch/pymqi#260] opened 2021-04-22 17:21 UTC
I have created 2 queue manager "QM1" and "QM2" and configured a channel "QM1toQM2" for sending and receiving (sender channel, receiver channel) msg and the channel is working fine. Now i tried to connect to the queue manager from python code using pymqi.

```
import pymqi

queue_manager = 'QM1'
channel = 'QM1toQM2'
host = '127.0.0.1'
port = '1414'
conn_info = '%s(%s)' % (host, port)

qmgr = pymqi.connect(queue_manager, channel, conn_info)
qmgr.disconnect()
print("done")
```

but i am getting the error as:
```
qmgr = pymqi.connect(queue_manager, channel, conn_info)
  File "C:\Python38\lib\site-packages\pymqi\__init__.py", line 3024, in connect
    qmgr.connect_tcp_client(queue_manager or '', CD(), channel, conn_info, user, password)
  File "C:\Python38\lib\site-packages\pymqi\__init__.py", line 1649, in connect_tcp_client
    self.connect_with_options(name, **kwargs)
  File "C:\Python38\lib\site-packages\pymqi\__init__.py", line 1624, in connect_with_options        
    raise MQMIError(rv[1], rv[2])
pymqi.MQMIError: MQI Error. Comp: 2, Reason 2539: FAILED: MQRC_CHANNEL_CONFIG_ERROR
```

i have checked the AMQERR01 log, its showing as
```
4/22/2021 22:36:07 - Process(17588.1) User(******) Program(python.exe)
                      Host(**********) Installation(Installation1)
                      VRMF(9.2.2.0)
                      Time(2021-04-22T17:06:07.720Z)
                      CommentInsert1(QM1toQM2)
                     
AMQ9547E: Type of remote channel not suitable for action requested.

EXPLANATION:
The operation requested cannot be performed because channel 'QM1toQM2' on the
remote machine is not of a suitable type.  For example, if the local channel is
defined as a sender the remote machine must define its channel as either a
receiver or requester.
ACTION:
Check that the channel name is specified correctly.  If it is, check that the
remote channel has been defined correctly.
```

I am new to this. Please, can anyone help me with this

**Comment by JoshMcMQ** [comment] 2021-04-22 17:43
MQ clients such as pymqi connect to channels of type SVRCONN not SDR or RCVR.

**Comment by mrkksparrow** [comment] 2021-04-22 17:46
how can i do the same with sever connection channel type

**Comment by JoshMcMQ** [comment] 2021-04-22 19:06
Your question is not clear and the issue is not specific to pymqi.  I suggest you review the free IBM MQ Developer Essentials Badge Learning path at [IBM MQ Developer](https://developer.ibm.com/components/ibm-mq/).

I'm closing this issue,  if you run into any pymqi specific issues feel free to open a new issue.

**Closed by JoshMcMQ** 2021-04-22 19:06 UTC
