### ISSUE TITLE
When using the bind mode to connect to the queue manager

### ISSUE THREAD

**Issue by ToNorthX** [dsuch/pymqi#73] opened 2018-08-03 14:56 UTC
hello dsuch:
    When using the bind mode to connect to the queue manager, error code 2058 appears, but my   queue manager name is facing it.
Mycode:
   queue_manager="QM1"
    qmgr = pymqi.connect(queue_manager)
    qmgr.disconnect()
 
Thank you

**Comment by xodat2** [comment] 2018-08-31 12:05
Hello,
I've got the same issue...
I've tried using amqsputc.exe and it works fine in bindings mode.

**Comment by JoshMcMQ** [comment] 2018-08-31 15:46
@tongwandouxiong and @xodat2 can either or both of you provide what your /var/mqm/errors/AMQERR01.LOG shows when you get the 2058?  (On windows it would be in the windows MQ DATA location under the errors directory.  This is not the "errors/AMQERR01.LOG" that falls under the qmgrs/<QMGRNAME> directory.

**Comment by xodat2** [comment] 2018-08-31 16:48
Hello,
There is no error in logs (see timestamps)

![pymqi_2058](https://user-images.githubusercontent.com/42867205/44925311-60546c80-ad4e-11e8-8d94-21c0fe6eca1c.JPG)

**Comment by JoshMcMQ** [comment] 2018-08-31 18:30
Can you try a trace "strmqtrc -p python.exe -t all -t detail"  recreate the error then stop it "endmqtrc -a".  Under the mq install folder in the trace folder it will create TRC files.  If nothing was there to start with it should have three, 1 is for strmqtrc, 1 for endmqtrc, the last will be for the python.exe, this is indicated at the top of the file.  Search for the MQRC_Q_MGR_NAME_ERROR error and see if that provides any help in the cause of the error, if you want you can post the file if not too big here and I'll review it to see if I can help you further.

**Comment by xodat2** [comment] 2018-08-31 20:13
Hi Josh,
I've found something interesting in trace:

--------}! xcsGetEnvironmentString (rc=xecE_E_**ENV_VAR_NOT_FOUND**)
Using default channel file name of AMQCLCHL.TAB
--------{  rflOpen
KeySize=20 Filename='O:\ProgramData\IBM\MQ\AMQCLCHL.TAB'
---------{  xcsCreateFile
File: 'O:\ProgramData\IBM\MQ\AMQCLCHL.TAB', access: -2147483648, sharing: 3, permissions: 1, disposition: 3, attributes: 268435456, ffstOnError: FALSE
fd: -1, error: 2
---------}! xcsCreateFile (rc=lpiRC_**FILE_TREE_CREATION_ERROR**)

So it seems that mq client(?) is trying to create amqchltab file, but it fails for some reason.
(O:\ProgramData\IBM\MQ\AMQCLCHL.TAB - this file doesn't exists)
The second error is that some variable is missing,
I've tried to add:
os.environ["MQSPREFIX"] = "P:\IBM\WebSphere MQ"
(this is where qmgrs directory is located)

Do you have any idea?
I'm attaching full trace.

[AMQ21164.0.TRC.zip](https://github.com/dsuch/pymqi/files/2341446/AMQ21164.0.TRC.zip)


Btw, thank you for help :)

**Comment by JoshMcMQ** [comment] 2018-09-01 05:34
Can you try setting the environment variable MQ_CONNECT_TYPE=STANDARD before you call the program and see if it makes any difference.  Also can you confirm if you have multiple installations on the server?  Is it possible the MIINS001 is associated with a different installation than the client libraries that python is picking up?

**Comment by dsuch** [comment] 2018-09-01 06:03
Hello @JoshMcMQ - I also thank you for the assistance that you are providing in this ticket and elsewhere!

**Comment by dsuch** [comment] 2018-09-01 07:29
@tongwandouxiong @xodat2 @JoshMcMQ - I have not used connections in bindings mode for many years now so I'm not clear what the current situation is.

But, if I remember it correctly, around the time of MQ 6.0 the case was that an application (such as PyMQI) compiled with support for connections in client mode could not connect in bindings mode. For sure the other way around was not possible for more obvious reasons.

Because almost everyone uses the client mode for TCP, this is what PyMQI is compiled as by default, as a client. Particularly, if you just run 'pip install pymqi' then this is the mode that you get installed.

I wonder if this is not the case here - can you check if recompiling PyMQI from source in bindings mode (aka server mode) helps?

Once you download PyMQI, please run this command:

```
$ python setup.py build server
```

You will note that it outputs a message such as  'Building PyMQI server 64bits' instead of the usual 'Building PyMQI client 64bits'.

**Comment by JoshMcMQ** [comment] 2018-09-01 09:50
@dsuch, what the compiler options that are used with "server" vs "client"?  (is it linking against mqm vs mqic?  As of MQ v7.1 this is no longer a requirement, and if I think the suggestion I provided above may work around the issue.

If you link to mqic, then it will default to CLIENT, but as of 7.1 you can override it with the env variable I mention above.  If you link to mqm, historically it was only for a binding connection to a queue manager local on the same server) it will now check both, first checking on for a local queue manager, if one is not found then checking for the various other environmental way to to connect as a client such as MQSERVER environment variable or CCDT channels.

See Morag Hughson's blog [IBM MQ Little Gem #30: MQ_CONNECT_TYPE](https://imwuc.socious.com/blog/ibm-mq-little-gem-30-mq_connect_type) for more info.

Note that with v8 and higher "redistributable" clients are now offered that you can just untar or unzip where you want, one draw back is that on Linux GCC by default only sets the RPATH, this means that the LD_LIBRARY_PATH is only looked at if the files are NOT found in the specified RPATH meaning if you had a local full MQ install at a older version and you wanted to run the app against a different Redist version, it would always use the libraries found in the RPATH location (ex: /opt/mqm/lib64).  If you add linker flag --enable-new-dtags, it will have both a RPATH and RUNPATH set to the specified -rpath value.   If a RUNPATH is specified the LD_LIBRARY_PATH if present will be checked before the RPATH/RUNPATH, so you can override it to use a different version of MQ.

**Comment by dsuch** [comment] 2018-09-01 09:55
@JoshMcMQ - ah, this is all very nice.

Yes, it is linking mqm vs. mqmic, or other libraries, depending on OS, e.g. mqmcs or mqmzse.

Just for the reference - all the options are in [setup.py](https://github.com/dsuch/pymqi/blob/master/code/setup.py).

**Comment by tongwandouxiong** [comment] 2018-09-03 10:04
@xodat2 Have you tried it？ I've tried to set the env variable, but it didn't solve the issue.And I don't understand install pymqi directly on the server?

**Comment by xodat2** [comment] 2018-09-03 10:09
Hi tongwandouxiong,
I haven't tried it yet.
By install pymqi drectly I mean that instead of copying python with compiled pymqi, I will compile pymqi on the server (install via pip)

By server I mean wintel server, because I'm running this script on remote host, not on my PC.

**Comment by tongwandouxiong** [comment] 2018-09-03 10:17
I installed pymqi via pip, but still can't,  I saw dsuch  say Once you download PyMQI, please run this command: $ python setup.py build server,I don't quite understand what it means, Dou you tried the way?

**Comment by JoshMcMQ** [comment] 2018-09-05 23:13
@dsuch @tongwandouxiong @xodat2

I have not had time to do a more extensive test of this myself, but from what I know based my quick tests I performed:
1. If you compile something with the "client" libraries option (ex: mqic), then the application can ONLY connect as a client and the MQ_CONNECT_TYPE environment variable has no effect on the behavior of the application.  From what Dariusz said package that is installed with `pip install pymqi` is built with `python setup.py build client` which will be linked to the "client" libraries.
2. If you compile something with the "server" libraries options (ex: mqm), then the application as of MQ v7.1 will attempt to see if there is a local queue manager to connect to with binding mode, if there is not it will then try to connect as a client going through all the ways MQ can look for client connection information (the list and order is long, but high level MQSERVER or CCDT).  In this case the MQ_CONNECT_TYPE environment variable can also be set to force it to try either only BINDING or only CLIENT.  Any version of MQ that does not support this has been out of support since September 2015 or earlier.

Based on what both of you have said you are using compiled file installed via `pip install pymqi`, so the solution is to compile this with `python setup.py build server`.  You should be able to compile this even on a machine with only MQ client installed as long as you are at v7.1 or higher and then copy over to the MQ server where the queue manager exists.

@dsuch given the current behavior of releases of MQ 7.1 and higher, maybe it is better to default the `pip install pymqi` version to the `python setup.py build server` since this will work with both server binding mode and client mode and is the more flexible option.  If anyone is running a version of MQ older than 7.1 then shame on them and they can manually compile with `python setup.py build client`.  This is just my suggestion :).  Note that compiling with "server" will not effect the MQCONNX methods, they will still work the same way.

**Comment by xodat2** [comment] 2018-09-06 06:59
Hi Josh,
Thank you for answer.
I've tried to install it by setup.py but there another issue...

FILE:build\temp.win32-2.7\Release\pymqi\pymqe.pyd.manifest
   Creating library build\temp.win32-2.7\Release\pymqi\pymqe.lib and object build\temp.win32-2.7\Release\pymqi\pymqe.exp
pymqe.obj : error LNK2019: unresolved external symbol _MQCONN referenced in function _pymqe_MQCONN
pymqe.obj : error LNK2019: unresolved external symbol _MQCONNX referenced in function _pymqe_MQCONNX
pymqe.obj : error LNK2019: unresolved external symbol _MQDISC referenced in function _pymqe_MQDISC
pymqe.obj : error LNK2019: unresolved external symbol _MQOPEN referenced in function _pymqe_MQOPEN
pymqe.obj : error LNK2019: unresolved external symbol _MQCLOSE referenced in function _pymqe_MQCLOSE
pymqe.obj : error LNK2019: unresolved external symbol _MQPUT1 referenced in function _mqputN
pymqe.obj : error LNK2019: unresolved external symbol _MQPUT referenced in function _mqputN
pymqe.obj : error LNK2019: unresolved external symbol _MQGET referenced in function _pymqe_MQGET
pymqe.obj : error LNK2019: unresolved external symbol _MQBEGIN referenced in function _pymqe_MQBEGIN
pymqe.obj : error LNK2019: unresolved external symbol _MQCMIT referenced in function _pymqe_MQCMIT
pymqe.obj : error LNK2019: unresolved external symbol _MQBACK referenced in function _pymqe_MQBACK
pymqe.obj : error LNK2019: unresolved external symbol _MQINQ referenced in function _pymqe_MQINQ
pymqe.obj : error LNK2019: unresolved external symbol _MQSET referenced in function _pymqe_MQSET
pymqe.obj : error LNK2019: unresolved external symbol _MQSUB referenced in function _pymqe_MQSUB
pymqe.obj : error LNK2019: unresolved external symbol _MQCRTMH referenced in function _pymqe_MQCRTMH
pymqe.obj : error LNK2019: unresolved external symbol _MQSETMP referenced in function _pymqe_MQSETMP
pymqe.obj : error LNK2019: unresolved external symbol _MQINQMP referenced in function _pymqe_MQINQMP
pymqe.obj : error LNK2019: unresolved external symbol _mqDeleteBag referenced in function _cleanupBags
pymqe.obj : error LNK2019: unresolved external symbol _mqInquireByteString referenced in function _pymqe_mqaiExecute
pymqe.obj : error LNK2019: unresolved external symbol _mqInquireString referenced in function _pymqe_mqaiExecute
pymqe.obj : error LNK2019: unresolved external symbol _mqInquireItemInfo referenced in function _pymqe_mqaiExecute
pymqe.obj : error LNK2019: unresolved external symbol _mqCountItems referenced in function _pymqe_mqaiExecute
pymqe.obj : error LNK2019: unresolved external symbol _mqInquireInteger referenced in function _pymqe_mqaiExecute
pymqe.obj : error LNK2019: unresolved external symbol _mqInquireBag referenced in function _pymqe_mqaiExecute
pymqe.obj : error LNK2019: unresolved external symbol _mqExecute referenced in function _pymqe_mqaiExecute
pymqe.obj : error LNK2019: unresolved external symbol _mqAddByteString referenced in function _pymqe_mqaiExecute
pymqe.obj : error LNK2019: unresolved external symbol _mqAddString referenced in function _pymqe_mqaiExecute
pymqe.obj : error LNK2019: unresolved external symbol _mqAddInteger referenced in function _pymqe_mqaiExecute
pymqe.obj : error LNK2019: unresolved external symbol _mqAddIntegerFilter referenced in function _pymqe_mqaiExecute
pymqe.obj : error LNK2019: unresolved external symbol _mqAddStringFilter referenced in function _pymqe_mqaiExecute
pymqe.obj : error LNK2019: unresolved external symbol _mqCreateBag referenced in function _pymqe_mqaiExecute
build\lib.win32-2.7\pymqi\pymqe.pyd : fatal error LNK1120: 31 unresolved externals
error: command 'C:\\Users\\AU01ID\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\link.exe' failed with exit status 1120

**Comment by JoshMcMQ** [comment] 2018-09-06 07:19
Do you have a full MQ install (either client or server should work) on the server where you are attempting the compile?  Has that version been set as the primary version?  You can check this with the `dspmqver` command and look for the value `Primary:     Yes`.  If it is not, try setting it as the primary and recompile.

**Comment by xodat2** [comment] 2018-09-06 09:59
Ok, I've managed to setup pymqi via setup.py (I've done that on virtual machine with clean MQ server install, visual studio etc).
It's working on that machine with queue managers, but after moving script with whole python to another system, there is again queue manager name issue.
I don't know if it's possible then to move compiled pymqi to another system.
Thank you.

**Comment by JoshMcMQ** [comment] 2018-09-06 10:53
@xodat2, does the machine you move it to have the same version of MQ server installed and is it marked as the Primary install?  And to clarify this is a server with queue managers you are attempting to connect to?

**Comment by xodat2** [comment] 2018-09-06 11:07
@JoshMcMQ
I've double checked everything, and after moving I forgot to change queue manager name....
(queue manager name was correct on attempts before, via PIP installed pymqi)
IT IS WORKING NOW!
So as you said, it have to be compiled via setup.py (I've also had to copy some missing ddl's)
Thank you very much Josh! I own you a beer :)

**Comment by JoshMcMQ** [comment] 2018-10-10 03:58
@tongwandouxiong Were you able to get server binding mode to work by installing with `python setup.py build server`?

@dsuch any thought into making that the default based on my comments above on September 5th?

**Comment by dsuch** [comment] 2018-10-10 06:45
Hi @JoshMcMQ - yes, making it work in both bindings and client mode makes sense. I will change it. This will be also a good time to rename ```server``` to ```bindings```, or at least to alias it. The previous naming was chosen 15+ years ago by someone else.

**Comment by dsuch** [comment] 2019-03-13 16:43
> This will be also a good time to rename server to bindings, or at least to alias it. 

This is done - now building PyMQI happens either in client or bindings mode. Using the 'server' mode on input to setup.py was left for backward compatibility.

Note, however, that ```pymqi.__mqbuild__``` will be equal to 'bindings' even if 'server' mode was used during compilation:

```
$ python setup.py build server
Building PyMQI bindings mode 64bit
...
$ python -c 'import pymqi; print(pymqi.__mqbuild__)'
bindings
$
```

For all intents and purposes, going forward, let's use the bindings mode name as in MQ.

**Closed by dsuch** 2019-03-13 16:43 UTC
